# Load remote theme: https://just-the-docs.github.io/just-the-docs/
remote_theme: just-the-docs/just-the-docs
logo: "/assets/logo-square128.png"

# Enable search.
search_enabled: true

# Heading anchors.
heading_anchors: true
